@startuml

' List entities with their notes -------------------------------------

package errors <<Frame>> #E0EBF5 {

    interface error {
        +Error() string
    }

}

package eliteConfiguration <<Frame>> #DD {

    note as packageMethods
        +New(requiredName string) Configuration
        +Load(fileName string) (Configuration, error)
        +Save(configuration Configuration, fileName string) error
        +Version() string
    end note

    interface Configuration {
        +Name() string
        +SetName(name string) Configuration
        +Value(name string) (interface{}, error)
        +Add(name string, value interface{}) Configuration
        +Remove(name string) Configuration
        +Size() int
        +Property(name string) Property
        +HasProperty(name string) bool
        #newProperty(name string, value interface{}) Property
        #properties() map[string]Property
    }

    interface Property {
        +Name() string
        +Value() interface{}
    }

    class marshallableConfiguration {
        +NameAttr string
        +PropertiesAttr map[string]property
    }

    class immutableConfiguration {
        #iName string
        #iProperties map[string]property
    }
    note right : used by Default

    class immutableProperty {
        #iName string
        #iValue interface{}
    }

    class marshallableProperty {
        +NameAttr string
        +ValueAttr interface{}
    }

    class configurationError {
        #message string
        #cause error
    }

}


' List relationships -------------------------------------------------

eliteConfiguration +-- errors

Configuration <|.. immutableConfiguration
error <|.. configurationError
Property <|.. immutableProperty
Configuration *-- "*" Property : contains >
marshallableConfiguration *-- "*" marshallableProperty : contains >


' Plant UML configuration --------------------------------------------

title
    EliteConfiguration Class Diagram
endtitle

legend center
    EliteSystems&#169; 2016
endlegend

hide empty members
hide empty fields
hide empty methods

@enduml